---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: stanza-metadata
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
metadata:
  name: stanza-metadata
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch"]
    resources:
      - pods
      - namespaces
      - replicasets
      - jobs
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stanza-metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stanza-metadata
subjects:
  - kind: ServiceAccount
    name: stanza-metadata
    namespace: default
---
kind: ConfigMap
metadata:
  name: stanza-config
  namespace: default
apiVersion: v1
data:
  config.yaml: |2-
    pipeline:
      - type: file_input
        include:
          - /var/log/containers/*
        write_to: message
        include_file_path: true

      - type: regex_parser
        parse_from: $labels.file_path
        regex: '^/var/log/containers/(?P<pod_name>.*)_(?P<namespace>.*)_(?P<service>.*)-[a-z0-9]+\.log'

      - type: restructure
        ops:
          - move:
              from: '$record.pod_name'
              to: '$resource["k8s.pod.name"]'
          - move:
              from: '$record.namespace'
              to: '$resource["k8s.namespace.name"]'

      - type: k8s_metadata_decorator

      - type: file_output
        path: /tmp/test.out
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stanza
  namespace: default
spec:
  selector:
    matchLabels:
      name: stanza
  template:
    metadata:
      labels:
        name: stanza
    spec:
      serviceAccountName: stanza-metadata
      containers:
        - name: stanza
          image: observiq/stanza:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
              cpu: 100m
            requests:
              memory: "250Mi"
              cpu: 100m
          volumeMounts:
            - mountPath: /stanza_home/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockerlogs
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockerlogs
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: stanza-config
