---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: carbon-metadata
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
metadata:
  name: carbon-metadata
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: carbon-metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carbon-metadata
subjects:
  - kind: ServiceAccount
    name: carbon-metadata
    namespace: default
---
kind: ConfigMap
metadata:
  name: carbon-config
  namespace: default
apiVersion: v1
data:
  config.yaml: |2-
    pipeline:
      - id: file_input
        type: file_input
        include:
          - /var/log/containers/*
        write_to: message
        file_path_field: path
        output: path_parser

      - id: path_parser
        type: regex_parser
        parse_from: path
        regex: '^/var/log/containers/(?P<pod_name>.*)_(?P<namespace>.*)_(?P<service>.*)-[a-z0-9]+\.log'
        output: k8s_metadata

      - id: k8s_metadata
        type: k8s_metadata_decorator
        output: file_out

      - id: file_out
        type: file_output
        path: /tmp/test.out
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: carbon
  namespace: default
spec:
  selector:
    matchLabels:
      name: carbon
  template:
    metadata:
      labels:
        name: carbon
    spec:
      serviceAccountName: carbon-metadata
      containers:
        - name: carbon
          image: observiq/carbon:0.0.0-alpha.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
              cpu: 100m
            requests:
              memory: "250Mi"
              cpu: 100m
          volumeMounts:
            - mountPath: /carbon_home/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockerlogs
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockerlogs
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: carbon-config
