---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: carbon-metadata
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
metadata:
  name: carbon-metadata
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: carbon-metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carbon-metadata
subjects:
  - kind: ServiceAccount
    name: carbon-metadata
    namespace: default
---
kind: ConfigMap
metadata:
  name: carbon-config
  namespace: default
apiVersion: v1
data:
  config.yaml: |2-
    pipeline:
      - type: aks
        container_log_path: /var/log/containers/*
        kubelet_journald_log_path: /var/log/journal
        start_at: beginning
      - type: drop_output
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: carbon
  namespace: default
spec:
  selector:
    matchLabels:
      name: carbon
  template:
    metadata:
      labels:
        name: carbon
    spec:
      serviceAccountName: carbon-metadata
      containers:
        - name: carbon
          image: observiq/carbon:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
              cpu: 100m
            requests:
              memory: "250Mi"
              cpu: 100m
          volumeMounts:
            - mountPath: /carbon_home/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockerlogs
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockerlogs
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: carbon-config
