name: Scan Licenses
on: [push, pull_request]
jobs:
  build:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Install Tools
        run: make install-tools

      - name: Scan
        run: make scan-license 
