name: Scan Licenses
on: [push, pull_request]
jobs:
  build:
    name: Scan Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install License Scanner
        run: go install github.com/uw-labs/lichen@latest

      - name: Check out source code
        uses: actions/checkout@v1

      # License scanner requires a built binary
      - name: Install Modules
        run: make build

      - name: Scan Licenses
        run: lichen --config=./license.yaml "./artifacts/stanza_linux_amd64"
